version: "3.7"
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e_menu_db
      - PGPORT=5432
    # volumes:
    #   - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    # volumes:
    #   - backend_data:/usr/src/app/uploads
  dashboard:
    build:
      context: ./dashboard
      dockerfile: .
    ports:
      - "3001:3001"
    depends_on:
      - backend
# volumes:
#   db_data:
#   backend_data:
